server:
  port: 8888
spring:
#  security:
#    user:
#      name: user #配置调试security的账号密码
#      password: 123
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootadmin?useSSL=false
    username: root
    password: YHXyhx1214+.
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB
  profiles:
    active: prod
  mvc:
    view:
      suffix: .jsp #访问jsp页面1
      prefix: / #访问jsp页面2
#    servlet:
#      path: /api #访问接口
  jpa:
    hibernate:
      ddl-auto: update #实体类自动生成数据库，更新状态，不会删除数据
    defer-datasource-initialization: true #1.自动初始化数据库
  sql: #初始化数据库
    init:
      schema-locations: classpath:sql/data.sql  #2.初始化数据库，DDL语句在resources/sql/schema.sql
      mode: never #第一次初始化数据库使用always，之后使用never
#      data-locations: classpath:sql/data.sql #3.初始化数据库，DML语句在resources/sql/data.sql #4.初始化数据库，每次启动都会初始化数据库

mybatis:
  mapper-locations: classpath:com/xxbb/mapper/*Mapper.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.xxbb.entity  # 注意：对应实体类的路径

# 输出mybatis日志
logging:
  level:
    com:
      spring:
        moonshiner:
          mapper: debug


# 下载地址：
upload:
  path: D:/Upload/ #上传文件的路径
  prefix: /fileData #访问前缀
#后台管理系统
admin:
  index: /admin #后台管理系统的访问路径